# ~/.ticker.yaml

show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 5 # seconds
currency: USD
currency-summary-only: false
sort: user
watchlist:
  - SNP
  - GOOGL
  - NVDA
  - NVDL
  - MSFT
  - AMZN
  - SOXL
  - CRWD
  - V
  - JBL
lots:
groups:
  - name: options
    watchlist:
    holdings:
      #- symbol:
      #  quantity: 17
      #  unit_cost: 159.10
      #  fixed_cost: 0
      - symbol: "NVDL240621C00230000"
        quantity: 1
        unit_cost: 54
